### ISSUE TITLE
ImportError: No module named lora.crypto

### ISSUE THREAD

**Issue by mariosmail** [jieter/python-lora#3]
Whatever i do i get this error "ImportError: No module named lora.crypto"

**Comment by jieter** [comment]
How did you install python-lora? Please tell me more about your environment. For example a python shell session showing how you try to import from python-lora like this:

```
$ mkvirtualenv test
(test) $ pip install python-lora
Collecting python-lora
Collecting cryptography==1.5.2 (from python-lora)
Requirement already satisfied (use --upgrade to upgrade): setuptools>=11.3 in /home/jieter/.virtualenvs/test/lib/python2.7/site-packages (from cryptography==1.5.2->python-lora)
Collecting enum34 (from cryptography==1.5.2->python-lora)
  Using cached enum34-1.1.6-py2-none-any.whl
Collecting ipaddress (from cryptography==1.5.2->python-lora)
  Using cached ipaddress-1.0.18-py2-none-any.whl
Collecting pyasn1>=0.1.8 (from cryptography==1.5.2->python-lora)
  Using cached pyasn1-0.2.3-py2.py3-none-any.whl
Collecting six>=1.4.1 (from cryptography==1.5.2->python-lora)
  Using cached six-1.10.0-py2.py3-none-any.whl
Collecting idna>=2.0 (from cryptography==1.5.2->python-lora)
  Using cached idna-2.5-py2.py3-none-any.whl
Collecting cffi>=1.4.1 (from cryptography==1.5.2->python-lora)
Collecting pycparser (from cffi>=1.4.1->cryptography==1.5.2->python-lora)
Installing collected packages: enum34, ipaddress, pyasn1, six, idna, pycparser, cffi, cryptography, python-lora
Successfully installed cffi-1.10.0 cryptography-1.5.2 enum34-1.1.6 idna-2.5 ipaddress-1.0.18 pyasn1-0.2.3 pycparser-2.17 python-lora-1.1.4 six-1.10.0
You are using pip version 8.0.2, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
(test) $ python
Python 2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from lora.crypto import loramac_decrypt
>>> 
```

**Comment by mariosmail** [comment]
Firstly I just clone the Git repository at my desktop and run the setup.py but didn't work. After that I noticed your Readme.md and the "cryptography requires cffi which in turn requires libffi-dev and python-dev" note so I did also these installs. 
I am working on win7 and spyder IDE


`C:\Users\R00158144>pip` install python-lora
Collecting python-lora
Requirement already satisfied: cryptography==1.5.2 in c:\programdata\anaconda2\l
ib\site-packages (from python-lora)
Requirement already satisfied: enum34 in c:\programdata\anaconda2\lib\site-packa
ges (from cryptography==1.5.2->python-lora)
Requirement already satisfied: idna>=2.0 in c:\programdata\anaconda2\lib\site-pa
ckages (from cryptography==1.5.2->python-lora)
Requirement already satisfied: cffi>=1.4.1 in c:\programdata\anaconda2\lib\site-
packages (from cryptography==1.5.2->python-lora)
Requirement already satisfied: setuptools>=11.3 in c:\programdata\anaconda2\lib\
site-packages\setuptools-27.2.0-py2.7.egg (from cryptography==1.5.2->python-lora)
Requirement already satisfied: ipaddress in c:\programdata\anaconda2\lib\site-pa
ckages (from cryptography==1.5.2->python-lora)
Requirement already satisfied: six>=1.4.1 in c:\programdata\anaconda2\lib\site-p
ackages (from cryptography==1.5.2->python-lora)
Requirement already satisfied: pyasn1>=0.1.8 in c:\programdata\anaconda2\lib\sit
e-packages (from cryptography==1.5.2->python-lora)
Requirement already satisfied: pycparser in c:\programdata\anaconda2\lib\site-pa
ckages (from cffi>=1.4.1->cryptography==1.5.2->python-lora)
Installing collected packages: python-lora
Successfully installed python-lora-1.1.4`

**Comment by jieter** [comment]
ok, now you should have `python-lora` installed properly, can you try to import it in a python shell?

**Comment by mariosmail** [comment]
Indeed!!! How that happened?

**Comment by jieter** [comment]
By the way, this is an issue tracker to report bugs and request features, not a place to ask for help on using the library. Please use [stackoverflow](http://stackoverflow.com/).

**Comment by mariosmail** [comment]
Ok. I am new to this mentality so sorry for any inconvinience and thank you

**Comment by jieter** [comment]
no problem, but would be nice next time.
